# Generated by Django 4.2.1 on 2023-05-23 00:23

import api_app.models.mahasiswa
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=9)),
                ('password', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(choices=[(api_app.models.mahasiswa.KelasMahasiswa['A'], 'A'), (api_app.models.mahasiswa.KelasMahasiswa['B'], 'B')], max_length=1)),
                ('tahun_masuk', models.PositiveIntegerField()),
                ('tahun_keluar', models.PositiveIntegerField()),
            ],
        ),
    ]
