# Generated by Django 4.2.1 on 2023-05-23 18:07

import api_app.models.item_akreditasi
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemAkreditasiMahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[(api_app.models.item_akreditasi.StatusAkreditasi['PENDING'], 'PENDING'), (api_app.models.item_akreditasi.StatusAkreditasi['VALID'], 'VALID'), (api_app.models.item_akreditasi.StatusAkreditasi['INVALID'], 'INVALID')], default=api_app.models.item_akreditasi.StatusAkreditasi['PENDING'], max_length=10)),
                ('bidang', models.CharField(choices=[(api_app.models.item_akreditasi.BidangAkreditasi['CPBidangSI'], 'CPBidangSI'), (api_app.models.item_akreditasi.BidangAkreditasi['CPBidangTI'], 'CPBidangTI'), (api_app.models.item_akreditasi.BidangAkreditasi['CPBidangIK'], 'CPBidangIK'), (api_app.models.item_akreditasi.BidangAkreditasi['CPBidangSK'], 'CPBidangSK'), (api_app.models.item_akreditasi.BidangAkreditasi['CPBidangRPL'], 'CPBidangRPL'), (api_app.models.item_akreditasi.BidangAkreditasi['PKM'], 'PKM'), (api_app.models.item_akreditasi.BidangAkreditasi['SertifikasiDosen'], 'SertifikasiDosen'), (api_app.models.item_akreditasi.BidangAkreditasi['SertifikatMahasiswa'], 'SertifikatMahasiswa')], max_length=20)),
                ('mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_app.mahasiswa')),
            ],
        ),
    ]
