# Generated by Django 4.2.1 on 2023-05-24 01:31

import api_app.models.dosen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_itemakreditasimahasiswa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=255)),
                ('nama', models.CharField(max_length=100)),
                ('bidang_studi', models.CharField(choices=[(api_app.models.dosen.BidangStudi['SI'], 'SI'), (api_app.models.dosen.BidangStudi['TI'], 'TI'), (api_app.models.dosen.BidangStudi['IK'], 'IK'), (api_app.models.dosen.BidangStudi['SK'], 'SK'), (api_app.models.dosen.BidangStudi['RPL'], 'RPL')], max_length=1)),
            ],
        ),
    ]
