# Generated by Django 4.2.1 on 2023-05-23 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_kaprodi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kaprodi',
            name='nip',
            field=models.CharField(max_length=20),
        ),
    ]
