# Generated by Django 4.2.1 on 2023-05-24 01:32

import api_app.models.dosen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_dosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='bidang_studi',
            field=models.CharField(choices=[(api_app.models.dosen.BidangStudi['SI'], 'SI'), (api_app.models.dosen.BidangStudi['TI'], 'TI'), (api_app.models.dosen.BidangStudi['IK'], 'IK'), (api_app.models.dosen.BidangStudi['SK'], 'SK'), (api_app.models.dosen.BidangStudi['RPL'], 'RPL')], max_length=3),
        ),
    ]
